language: node_js

node_js:
  - "8"
  - "9"
  - "10"
  - "stable"

cache:
  directories:
    - node_modules

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - yarn test

after_script:
  - yarn test:codecov
  - ./cc-test-reporter after-build --exit-code "${TRAVIS_TEST_RESULT}"

notifications:
  email: false
  slack:
    rooms:
      - secure: "AhlRx+cDugPFgURPLljxBji0utenbk+56ZHZw2iLiIuZL1BgUQKWZpQaMV0T55YTMQF7PrpCpOdL4UXgM08cbXUDCJr4LscbuwFPltVgyZC1MbCopxcp559VXcXYxEyTmzOjGCWwpCz4JQY20KYcMLrnNWust7O//Ti77vEqpaUCdfX0BhkFlqRVEdjP1gCWq+iOoDIPDzCd7iE6EyVxRntwL+RCCZ7NO8Z9oC3sL2ms2RmXmrYHDruHAhpoIudhNOBMQ1cSUrF9ZtHvdcqUGrb0j2QLc/exASc93499mlVl88Ip82D5HKgcDV3pUrNvl4vQI6BRtRKSJlLpA4/kUaU6tGXi0Lt0LYdp2yfwY/X+QEz+1ybpi2SkcfDxJyr4lFg+U3+t2GkoziQmS6RCjOR22JIkeAlWshe8hZx7XucMAaLZ17rOMXluRlFdIB3rAgwDphdTXqcQ63psvJsVSU1NjAs+EoefNP6/z9WQQgmHajNqR6m/cnx38fAYNlfNZ9Eje7jwci9F3wTM4Q0lPyKjefx1DyBGJlN31Ku8OyGLZn0v8agA9hWpJ5TyWg3MVZ5AheJGUcUONqXvthk+uF8xRPOGjUvvfhlZHexaqskyxf14JGrzep9jdQqtf0Ggue4JCBOrNI9X7rRi+SnIbFdexa/7gk7jL3OdqlqNTJg="
