name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions: read-all

env:
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node_version: [14.x, 16.x, 18.x]
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        id: node
        with:
          node-version: ${{ matrix.node_version }}
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            Node.js: ${{ steps.node.outputs.node-version }}
          status: in-progress
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --ignore-scripts
        env:
          NODE_ENV: development
      - name: Build
        run: yarn build
        env:
          NODE_ENV: production
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            Node.js: ${{ steps.node.outputs.node-version }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node_version: [19.x]
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        id: node
        with:
          node-version: ${{ matrix.node_version }}
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            Node.js: ${{ steps.node.outputs.node-version }}
            ESLint issues: Checking...
            Prettier issues: Checking...
          status: in-progress
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --ignore-scripts
        env:
          NODE_ENV: development
      - name: Lint
        id: lint
        run: |
          yarn ci:eslint || true
          yarn ci:prettier || true
          yarn lint || true
      - name: Lint results
        id: lint-results
        run: |
          export LINT_ISSUES=$((${{ steps.lint.outputs.eslint-issues || 0 }} + ${{ steps.lint.outputs.prettier-issues || 0 }}))
          if [ "${LINT_ISSUES}" -eq 0 ]; then exit 0; else exit 1; fi
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            Node.js: ${{ steps.node.outputs.node-version }}
            ESLint issues: ${{ steps.lint.outputs.eslint-issues || 'Skipped' }}
            Prettier issues: ${{ steps.lint.outputs.prettier-issues || 'Skipped' }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node_version: [14.x, 16.x, 18.x]
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        id: node
        with:
          node-version: ${{ matrix.node_version }}
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            Node.js: ${{ steps.node.outputs.node-version }}
            Total / Passed: Checking...
            Coverage: Checking...
          status: in-progress
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --ignore-scripts
        env:
          NODE_ENV: development
      - name: Test
        id: test
        run: yarn ci:test
      - name: Send Codecov report
        if: ${{ !env.ACT && github.event_name != 'pull_request' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Send Code Climate report
        uses: paambaati/codeclimate-action@v5.0.0
        if: ${{ !env.ACT && github.event_name != 'pull_request' }}
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            Node.js: ${{ steps.node.outputs.node-version }}
            Total / Passed: ${{ steps.test.outputs.total || 0 }} / ${{ steps.test.outputs.passed || 0 }}
            Coverage: ${{ steps.test.outputs.coverage || 'Skipped' }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}
